{"uuid":"01a92fb5-1e75-4913-b282-e2c3db5d3530","historyId":"53a1a5e53c94c4924f75487a689fce76","fullName":"task_20.Task20_Test.testAddition","labels":[{"name":"package","value":"task_20.Task20_Test"},{"name":"testClass","value":"task_20.Task20_Test"},{"name":"testMethod","value":"testAddition"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Java_AQA"},{"name":"subSuite","value":"task_20.Task20_Test"},{"name":"host","value":"MacBook-Air-Dmitro.local"},{"name":"thread","value":"71505@MacBook-Air-Dmitro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testAddition","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The addition result is incorrect expected [Expected_Result] but found [8]","trace":"java.lang.AssertionError: The addition result is incorrect expected [Expected_Result] but found [8]\n\tat org.testng.Assert.fail(Assert.java:96)\n\tat org.testng.Assert.failNotEquals(Assert.java:776)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:137)\n\tat org.testng.Assert.assertEquals(Assert.java:118)\n\tat org.testng.Assert.assertEquals(Assert.java:453)\n\tat task_20.Task20_Test.testAddition(Task20_Test.java:43)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\n\tat org.testng.TestRunner.run(TestRunner.java:505)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\n\tat org.testng.TestNG.run(TestNG.java:1017)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","steps":[],"attachments":[{"name":"Screenshot","source":"a6574355-4c64-4842-9768-d036e47c1ca5-attachment","type":"image/png"},{"name":"Addition Result","source":"68b19aba-e979-4f06-ab59-04b331e71d1d-attachment","type":"text/plain"},{"name":"Failure Screenshot for testAddition","source":"b81e8821-2817-4ce3-95ec-4d8ca459ecc2-attachment","type":"image/png"}],"parameters":[],"start":1734951044883,"stop":1734951048659}